version: "3.11"

services:
#  fastapi_app:
#    build: .
#    volumes:
#      - .:/src
#    ports:
#      - "8000:8000"
#    environment:
#      - REDIS_HOSTS=local:redis:6379
#    depends_on:
#      - db


  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapi
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
